name: Beam2
version: '1.0'
main: org.kisten.beam2.Beam2
api-version: '1.20'
commands:
  laser:
    description: "Spawning laser beam"
    usage: "/laser"
    aliases: [laser]
    permission: beam2.command.laser
    permission-message: "You don't have permission to spawn a laser beam"